# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jonbell-grip}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Nunemaker", "Jonathan Bell"]
  s.date = %q{2010-03-25}
  s.description = %q{Attachment plugin for MongoMapper that uses GridFS.}
  s.email = %q{nunemaker@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/grip.rb",
     "lib/grip/version.rb",
     "test/fixtures/cthulhu.png",
     "test/fixtures/sample.pdf",
     "test/helper.rb",
     "test/test_grip.rb"
  ]
  s.homepage = %q{http://github.com/jonbell/grip}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Attachment plugin for MongoMapper that uses GridFS.}
  s.test_files = [
    "test/helper.rb",
     "test/test_grip.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<wand>, [">= 0.2.1"])
      s.add_development_dependency(%q<mongo_mapper>, ["= 0.7.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<wand>, [">= 0.2.1"])
      s.add_dependency(%q<mongo_mapper>, ["= 0.7.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<wand>, [">= 0.2.1"])
    s.add_dependency(%q<mongo_mapper>, ["= 0.7.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

